// list of independent channels
// videoDuration and subs count are not used yet
const channelsOriginal = [
  // -- channels for auto-play ------------
  { id: 1,
    url: 'https://www.youtube.com/channel/UCgpSieplNxXxLXYAzJLLpng',
    urls: ['https://www.youtube.com/channel/UCgpSieplNxXxLXYAzJLLpng'],
    name: 'Майкл Наки (Michael Naki)',
    videoDurationMin: 20,
    subsThousand: 400,
    play: true,
  },
  { id: 2,
    name: 'DW',
    url: 'https://www.youtube.com/channel/UCXoAjrdHFa2hEL3Ug8REC1w',
    urls: ['https://www.youtube.com/channel/UCXoAjrdHFa2hEL3Ug8REC1w'],
    videoDurationMin: 20,
    subsThousand: 900,
  },
  { id: 3,
    name: 'Екатерина Шульман (Ekaterina Shulman)',
    url: 'https://www.youtube.com/channel/UCL1rJ0ROIw9V1qFeIN0ZTZQ',
    urls: ['https://www.youtube.com/channel/UCL1rJ0ROIw9V1qFeIN0ZTZQ', '/channel/UCL1rJ0ROIw9V1qFeIN0ZTZQ'],
    videoDurationMin: 20,
    subsThousand: 730,
    play: true,
  },
  { id: 4,
    name: 'Владимир Милов (Vladimir Milov)',
    url: 'https://www.youtube.com/channel/UCjQdM9q_Vd2gBN9Xy_zRDJQ',
    urls: ['https://www.youtube.com/channel/UCjQdM9q_Vd2gBN9Xy_zRDJQ'],
    videoDurationMin: 20,
    subsThousand: 300,
    play: true,
  },
  { id: 5,
    name: 'Навальный LIVE (Navalny LIVE)',
    url: 'https://www.youtube.com/channel/UCgxTPTFbIbCWfTR9I2-5SeQ',
    urls: ['https://www.youtube.com/channel/UCgxTPTFbIbCWfTR9I2-5SeQ', '/c/NavalnyLiveChannel'],
    videoDurationMin: 20,
    subsThousand: 2500 * 0.7,
    play: true,
  },
  { id: 6,
    name: 'Yulia Latynina',
    url: 'https://www.youtube.com/channel/UCzaqqlriSjVyc795m86GVyg',
    urls: ['https://www.youtube.com/channel/UCzaqqlriSjVyc795m86GVyg'],
    videoDurationMin: 20,
    subsThousand: 300,
    play: true,
  },
  { id: 7,
    name: 'Popular Politics',
    url: 'https://www.youtube.com/channel/UC7Elc-kLydl-NAV4g204pDQ',
    urls: ['https://www.youtube.com/channel/UC7Elc-kLydl-NAV4g204pDQ'],
    videoDurationMin: 10,
    subsThousand: 600,
    play: true,
  },
  { id: 8,
    name: 'Михаил Ходорковский (Michail Khodorkovsky)',
    url: 'https://www.youtube.com/c/khodorkovskyru',
    urls: ['https://www.youtube.com/channel/UCAg74TJrwfpuCp1Jo3ZHMjA', '/c/khodorkovskyru'],
    videoDurationMin: 10,
    subsThousand: 1000,
    play: true,
  },
  { id: 9,
    name: 'Дмитрий ПОТАПЕНКО (Dimitry Potapenko)',
    url: 'https://www.youtube.com/channel/UC54SBo5_usXGEoybX1ZVETQ',
    urls: ['https://www.youtube.com/channel/UC54SBo5_usXGEoybX1ZVETQ'],
    videoDurationMin: 15,
    subsThousand: 700,
    play: true,
  },
  { id: 10,
    url: 'https://www.youtube.com/channel/UCoHH5raTevyI35tfb1YF6qA',
    urls: ['https://www.youtube.com/channel/UCoHH5raTevyI35tfb1YF6qA'],
    videoDurationMin: 10,
    subsThousand: 950,
    name: 'Илья Яшин (Ilya Yashin)',
    play: true,
  },
  { id: 11,
    url: 'https://www.youtube.com/channel/UCiWMFQCGvwGSc8QWHOqcQhw',
    urls: ['https://www.youtube.com/channel/UCiWMFQCGvwGSc8QWHOqcQhw'],
    videoDurationMin: 2,
    subsThousand: 1600 * 0.5,
    name: 'Радио Свобода (Radio Freedon)',
    play: true,
  },
  { id: 12,
    url: 'https://www.youtube.com/channel/UCfD6O-n4-Sw7r3xci7YStgg',
    urls: ['https://www.youtube.com/channel/UCfD6O-n4-Sw7r3xci7YStgg'],
    videoDurationMin: 2,
    subsThousand: 4,
    name: 'Альянс учителей (Teachers Community)',
    play: true,
  },
  { id: 13,
    url: 'https://www.youtube.com/channel/UC2CoZtMc68lhBrupCOIvllw',
    urls: ['https://www.youtube.com/channel/UC2CoZtMc68lhBrupCOIvllw'],
    videoDurationMin: 5,
    subsThousand: 77,
    name: 'The Insider',
    play: true,
  },
  { id: 14,
    url: 'https://www.youtube.com/channel/UC0p3rxtSGCnO-JjBz5bU5CQ',
    urls: ['https://www.youtube.com/channel/UC0p3rxtSGCnO-JjBz5bU5CQ'],
    videoDurationMin: 10,
    subsThousand: 100,
    name: 'Котрикадзе Дзядко (Kotrikadze Dzyadko)',
    play: true,
  },
  /*
  { id: 15,
    url: 'https://www.youtube.com/channel/UCb64k6yqn3s4DlayVkbJ2qw',
    urls: ['https://www.youtube.com/channel/UCb64k6yqn3s4DlayVkbJ2qw'],
    videoDurationMin: 5,
    subsThousand: 600,
    name: 'Обманутый Россиянин',
    play: true,
  },
  */


  // -- channels for likes ---------------
  { id: 16,
    url: 'https://www.youtube.com/channel/UCUGfDbfRIx51kJGGHIFo8Rw',
    urls: ['https://www.youtube.com/channel/UCUGfDbfRIx51kJGGHIFo8Rw'],
    videoDurationMin: 15,
    subsThousand: 990,
    name: 'Максим Кац (Max Katz)', // refused to participate
    play: false,
  },
  { id: 17,
    url: 'https://www.youtube.com/channel/UCBG57608Hukev3d0d-gvLhQ',
    urls: ['https://www.youtube.com/channel/UCBG57608Hukev3d0d-gvLhQ'],
    videoDurationMin: 10,
    subsThousand: 2400 * 0.5,
    name: 'Настоящее Время (Current Time TV)',
    play: false,
  },
  { id: 18,
    url: 'https://www.youtube.com/channel/UCsAw3WynQJMm7tMy093y37A',
    urls: ['https://www.youtube.com/channel/UCsAw3WynQJMm7tMy093y37A'],
    videoDurationMin: 5,
    subsThousand: 6400 * 0.25,
    name: 'Алексей Навальный (Aleksey Navalny)',
    play: false,
  },
  { id: 19,
    url: 'https://www.youtube.com/channel/UC1eFXmJNkjITxPFWTy6RsWg',
    urls: ['https://www.youtube.com/channel/UC1eFXmJNkjITxPFWTy6RsWg'],
    videoDurationMin: 10,
    subsThousand: 2800 * 0.5,
    name: 'Редакция',
    play: false,
  },
  { id: 20,
    url: 'https://www.youtube.com/channel/UC101o-vQ2iOj9vr00JUlyKw',
    urls: ['https://www.youtube.com/channel/UC101o-vQ2iOj9vr00JUlyKw'],
    videoDurationMin: 30,
    subsThousand: 3420 * 0.5,
    name: 'varlamov',
    play: false,
  },
  { id: 21,
    url: 'https://www.youtube.com/channel/UCBzDAjLfvBUBVMMP6-K-y0w',
    urls: ['https://www.youtube.com/channel/UCBzDAjLfvBUBVMMP6-K-y0w'],
    videoDurationMin: 30,
    subsThousand: 422,
    name: 'Ходорковский LIVE ',
    play: false,
  },
  { id: 22,
    url: 'https://www.youtube.com/channel/UCpJuziZAwEFnoeNGSaxQlCQ',
    urls: ['https://www.youtube.com/channel/UCpJuziZAwEFnoeNGSaxQlCQ'],
    videoDurationMin: 30,
    subsThousand: 905,
    name: 'Скажи Гордеевой ',
    play: false,
  },
  { id: 23,
    url: 'https://www.youtube.com/channel/UCnRR-BtJ7dL3azi2XC09JBA',
    urls: ['https://www.youtube.com/channel/UCnRR-BtJ7dL3azi2XC09JBA'],
    videoDurationMin: 30,
    subsThousand: 905,
    name: 'Masyanya Kuvaeva ',
    play: false,
  },
];
