// list of independent channels
// videoDuration and subs count are not used yet
const channelsOriginal = [
  // -- channels for auto-play ------------
  { id: 1,
    name: 'Майкл Наки (Michael Naki)',
    url: 'https://www.youtube.com/c/MackNack',
    urls: ['https://www.youtube.com/channel/UCgpSieplNxXxLXYAzJLLpng', 'www.youtube.com/c/MackNack'],
    videoDurationMin: 20,
    subsThousand: 400,
    play: true,
  },
  { id: 2,
    name: 'DW',
    url: 'https://www.youtube.com/channel/UCXoAjrdHFa2hEL3Ug8REC1w',
    urls: ['https://www.youtube.com/channel/UCXoAjrdHFa2hEL3Ug8REC1w', 'www.youtube.com/c/dwrussian'],
    videoDurationMin: 20,
    subsThousand: 900,
  },
  { id: 3,
    name: 'Екатерина Шульман (Ekaterina Shulman)',
    url: 'https://www.youtube.com/channel/UCL1rJ0ROIw9V1qFeIN0ZTZQ',
    urls: ['https://www.youtube.com/channel/UCL1rJ0ROIw9V1qFeIN0ZTZQ', '/channel/UCL1rJ0ROIw9V1qFeIN0ZTZQ'],
    videoDurationMin: 20,
    subsThousand: 730,
    play: true,
  },
  { id: 4,
    name: 'Владимир Милов (Vladimir Milov)',
    url: 'https://www.youtube.com/channel/UCjQdM9q_Vd2gBN9Xy_zRDJQ',
    urls: ['https://www.youtube.com/channel/UCjQdM9q_Vd2gBN9Xy_zRDJQ', 'www.youtube.com/c/%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%9C%D0%B8%D0%BB%D0%BE%D0%B2%D0%A3%D1%80%D1%83%D1%80%D1%83'],
    videoDurationMin: 20,
    subsThousand: 300,
    play: true,
  },
  { id: 5,
    name: 'Навальный LIVE (Navalny LIVE)',
    url: 'https://www.youtube.com/channel/UCgxTPTFbIbCWfTR9I2-5SeQ',
    urls: ['https://www.youtube.com/channel/UCgxTPTFbIbCWfTR9I2-5SeQ', '/c/NavalnyLiveChannel'],
    videoDurationMin: 20,
    subsThousand: 2500 * 0.7,
    play: true,
  },
  { id: 6,
    name: 'Yulia Latynina',
    url: 'https://www.youtube.com/channel/UCzaqqlriSjVyc795m86GVyg',
    urls: ['https://www.youtube.com/channel/UCzaqqlriSjVyc795m86GVyg'],
    videoDurationMin: 20,
    subsThousand: 300,
    play: true,
  },
  { id: 7,
    name: 'Popular Politics',
    url: 'https://www.youtube.com/channel/UC7Elc-kLydl-NAV4g204pDQ',
    urls: ['https://www.youtube.com/channel/UC7Elc-kLydl-NAV4g204pDQ', 'www.youtube.com/c/%D0%9F%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D0%B0%D1%8F%D0%BF%D0%BE%D0%BB%D0%B8%D1%82%D0%B8%D0%BA%D0%B0'],
    videoDurationMin: 10,
    subsThousand: 600,
    play: true,
  },
  { id: 8,
    name: 'Михаил Ходорковский (Michail Khodorkovsky)',
    url: 'https://www.youtube.com/c/khodorkovskyru',
    urls: ['https://www.youtube.com/channel/UCAg74TJrwfpuCp1Jo3ZHMjA', '/c/khodorkovskyru'],
    videoDurationMin: 10,
    subsThousand: 1000,
    play: true,
  },
  { id: 9,
    name: 'Дмитрий ПОТАПЕНКО (Dimitry Potapenko)',
    url: 'https://www.youtube.com/channel/UC54SBo5_usXGEoybX1ZVETQ',
    urls: ['www.youtube.com/channel/UC54SBo5_usXGEoybX1ZVETQ', 'www.youtube.com/c/%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B9%D0%9F%D0%9E%D0%A2%D0%90%D0%9F%D0%95%D0%9D%D0%9A%D0%9E-%D0%A2%D0%92'],
    videoDurationMin: 15,
    subsThousand: 700,
    play: true,
  },
  { id: 10,
    url: 'https://www.youtube.com/channel/UCoHH5raTevyI35tfb1YF6qA',
    urls: ['https://www.youtube.com/channel/UCoHH5raTevyI35tfb1YF6qA', 'www.youtube.com/c/%D0%98%D0%BB%D1%8C%D1%8F%D0%AF%D1%88%D0%B8%D0%BD1983'],
    videoDurationMin: 10,
    subsThousand: 950,
    name: 'Илья Яшин (Ilya Yashin)',
    play: true,
  },
  { id: 11,
    url: 'https://www.youtube.com/channel/UCiWMFQCGvwGSc8QWHOqcQhw',
    urls: ['www.youtube.com/channel/UCiWMFQCGvwGSc8QWHOqcQhw', 'www.youtube.com/c/SvobodaRadio'],
    videoDurationMin: 2,
    subsThousand: 1600 * 0.5,
    name: 'Радио Свобода (Radio Freedon)',
    play: true,
  },
  { id: 12,
    url: 'https://www.youtube.com/channel/UCfD6O-n4-Sw7r3xci7YStgg',
    urls: ['https://www.youtube.com/channel/UCfD6O-n4-Sw7r3xci7YStgg'],
    videoDurationMin: 2,
    subsThousand: 4,
    name: 'Альянс учителей (Teachers Community)',
    play: true,
  },
  { id: 13,
    url: 'https://www.youtube.com/channel/UC2CoZtMc68lhBrupCOIvllw',
    urls: ['https://www.youtube.com/channel/UC2CoZtMc68lhBrupCOIvllw', 'www.youtube.com/c/TheInsiderVideo'],
    videoDurationMin: 5,
    subsThousand: 77,
    name: 'The Insider',
    play: true,
  },
  { id: 14,
    name: 'Котрикадзе Дзядко (Kotrikadze Dzyadko)',
    url: 'https://www.youtube.com/channel/UC0p3rxtSGCnO-JjBz5bU5CQ',
    urls: ['https://www.youtube.com/channel/UC0p3rxtSGCnO-JjBz5bU5CQ', 'www.youtube.com/user/tdzyadko'],
    videoDurationMin: 10,
    subsThousand: 100,
    play: true,
  },
  { id: 15,
    url: 'https://www.youtube.com/channel/UC101o-vQ2iOj9vr00JUlyKw',
    urls: ['https://www.youtube.com/channel/UC101o-vQ2iOj9vr00JUlyKw', 'www.youtube.com/c/ivarlamov'],
    videoDurationMin: 30,
    subsThousand: 3420 * 0.5,
    name: 'varlamov',
    play: true,
  },


  // -- channels for likes ---------------
  { id: 16,
    url: 'https://www.youtube.com/channel/UCb64k6yqn3s4DlayVkbJ2qw',
    urls: ['https://www.youtube.com/channel/UCb64k6yqn3s4DlayVkbJ2qw', 'www.youtube.com/c/%D0%9E%D0%B1%D0%BC%D0%B0%D0%BD%D1%83%D1%82%D1%8B%D0%B9%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F%D0%BD%D0%B8%D0%BD'],
    videoDurationMin: 5,
    subsThousand: 600,
    name: 'Обманутый Россиянин',
    play: false,
  },
  { id: 17,
    url: 'https://www.youtube.com/channel/UCUGfDbfRIx51kJGGHIFo8Rw',
    urls: ['https://www.youtube.com/channel/UCUGfDbfRIx51kJGGHIFo8Rw', 'www.youtube.com/c/maxkatz1'],
    videoDurationMin: 15,
    subsThousand: 990,
    name: 'Максим Кац (Max Katz)', // refused to participate
    play: false,
  },
  { id: 18,
    url: 'https://www.youtube.com/channel/UCBG57608Hukev3d0d-gvLhQ',
    urls: ['https://www.youtube.com/channel/UCBG57608Hukev3d0d-gvLhQ', 'www.youtube.com/c/CurrenttimeTvofficial'],
    videoDurationMin: 10,
    subsThousand: 2400 * 0.5,
    name: 'Настоящее Время (Current Time TV)',
    play: false,
  },
  { id: 19,
    url: 'https://www.youtube.com/channel/UCsAw3WynQJMm7tMy093y37A',
    urls: ['https://www.youtube.com/channel/UCsAw3WynQJMm7tMy093y37A', 'www.youtube.com/c/%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B5%D0%B9%D0%9D%D0%B0%D0%B2%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9'],
    videoDurationMin: 5,
    subsThousand: 6400 * 0.25,
    name: 'Алексей Навальный (Aleksey Navalny)',
    play: false,
  },
  { id: 20,
    url: 'https://www.youtube.com/channel/UChccvlH7O3ch8cfc221rAXA',
    urls: ['https://www.youtube.com/channel/UChccvlH7O3ch8cfc221rAXA', 'www.youtube.com/c/VarlamovTalks'],
    videoDurationMin: 30,
    subsThousand: 3420 * 0.5,
    name: 'Varlamov Talks',
    play: false,
  },
  { id: 21,
    url: 'https://www.youtube.com/channel/UCBzDAjLfvBUBVMMP6-K-y0w',
    urls: ['https://www.youtube.com/channel/UCBzDAjLfvBUBVMMP6-K-y0w', 'www.youtube.com/c/khodorkovskylive'],
    videoDurationMin: 30,
    subsThousand: 422,
    name: 'Ходорковский LIVE ',
    play: false,
  },
  { id: 22,
    url: 'https://www.youtube.com/channel/UCpJuziZAwEFnoeNGSaxQlCQ',
    urls: ['https://www.youtube.com/channel/UCpJuziZAwEFnoeNGSaxQlCQ', 'www.youtube.com/c/skazhigordeevoy'],
    videoDurationMin: 30,
    subsThousand: 905,
    name: 'Скажи Гордеевой ',
    play: false,
  },
  { id: 23,
    url: 'https://www.youtube.com/channel/UCnRR-BtJ7dL3azi2XC09JBA',
    urls: ['https://www.youtube.com/channel/UCnRR-BtJ7dL3azi2XC09JBA', 'www.youtube.com/c/MasyanyaKuvaeva'],
    videoDurationMin: 30,
    subsThousand: 905,
    name: 'Masyanya Kuvaeva ',
    play: false,
  },
  { id: 24,
    url: 'https://www.youtube.com/channel/UCp2J7GRxQ36QLqW4ReLLt5g',
    urls: ['https://www.youtube.com/channel/UCp2J7GRxQ36QLqW4ReLLt5g'],
    videoDurationMin: 30,
    subsThousand: 2200,
    name: 'A поговорить?',
    play: false,
  },
  { id: 25,
    url: 'https://www.youtube.com/channel/UCBhBrcY15zuvDi6NpYUv3gw',
    urls: ['https://www.youtube.com/channel/UCBhBrcY15zuvDi6NpYUv3gw'],
    videoDurationMin: 5,
    subsThousand: 307,
    name: 'Мой протест Reserve',
    play: false,
  },
  { id: 26,
    url: 'https://www.youtube.com/channel/UCM326iLPPGxSoXZu6GFgu4Q',
    urls: ['https://www.youtube.com/channel/UCM326iLPPGxSoXZu6GFgu4Q', 'www.youtube.com/c/DetoxBrainwash'],
    videoDurationMin: 5,
    subsThousand: 0.6,
    name: 'Detox Brainwash',
    play: false,
  },
  { id: 27,
    url: 'https://www.youtube.com/channel/UC1eFXmJNkjITxPFWTy6RsWg',
    urls: ['https://www.youtube.com/channel/UC1eFXmJNkjITxPFWTy6RsWg', 'www.youtube.com/c/%D0%A0%D0%B5%D0%B4%D0%B0%D0%BA%D1%86%D0%B8%D1%8F'],
    videoDurationMin: 10,
    subsThousand: 2800 * 0.5,
    name: 'Редакция',
    play: false,
  },
  { id: 28,
    url: 'https://www.youtube.com/channel/UC6NQtwx4Bl7Ua_cvtiNe3Fw',
    urls: ['https://www.youtube.com/channel/UC6NQtwx4Bl7Ua_cvtiNe3Fw'],
    videoDurationMin: 10,
    subsThousand: 155,
    name: 'Leonid Volkov',
    play: false,
  },
  { id: 29,
    url: 'https://www.youtube.com/channel/UCI4hEQc8mkuK2eMsew_MwTw',
    urls: ['https://www.youtube.com/channel/UCI4hEQc8mkuK2eMsew_MwTw', 'www.youtube.com/c/%D0%9B%D1%8E%D0%B1%D0%BE%D0%B2%D1%8C%D0%A1%D0%BE%D0%B1%D0%BE%D0%BB%D1%8C%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D1%8F'],
    videoDurationMin: 10,
    subsThousand: 133,
    name: 'Любовь Соболь',
    play: false,
  },
  { id: 30,
    url: 'https://www.youtube.com/channel/UCZ-ix1fUTguJvwj6sxgF-6A',
    urls: ['https://www.youtube.com/channel/UCZ-ix1fUTguJvwj6sxgF-6A', 'www.youtube.com/c/%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9%D0%93%D1%83%D1%80%D0%B8%D0%B5%D0%B21'],
    videoDurationMin: 30,
    subsThousand: 318,
    name: 'Сергей Гуриев',
    play: false,
  },
  { id: 31,
    url: 'https://www.youtube.com/channel/UCwY0N0ZfxLz6XhTupuV0L0A',
    urls: ['https://www.youtube.com/channel/UCwY0N0ZfxLz6XhTupuV0L0A', 'www.youtube.com/c/DmitryGudkovRu'],
    videoDurationMin: 30,
    subsThousand: 54,
    name: 'Дмитрий Гудков',
    play: false,
  },
  { id: 32,
    url: 'https://www.youtube.com/channel/UCQVtD_N4OeD-9PshBq7NwyQ',
    urls: ['https://www.youtube.com/channel/UCQVtD_N4OeD-9PshBq7NwyQ', 'www.youtube.com/c/FeyginLive'],
    videoDurationMin: 30,
    subsThousand: 54,
    name: 'ФЕЙГИН LIVE',
    play: false,
  },
  { id: 33,
    url: 'https://www.youtube.com/channel/UCrp2It0yWUC7XcrWyBIQeKw',
    urls: ['https://www.youtube.com/channel/UCrp2It0yWUC7XcrWyBIQeKw', 'www.youtube.com/c/NEXTALive'],
    videoDurationMin: 30,
    subsThousand: 579,
    name: 'NEXTA Live',
    play: false,
  },
  { id: 33,
    url: 'https://www.youtube.com/channel/UCTVk323gzizpujtn2T_BL7w',
    urls: ['https://www.youtube.com/channel/UCTVk323gzizpujtn2T_BL7w', 'www.youtube.com/c/plushev'],
    videoDurationMin: 30,
    subsThousand: 156,
    name: 'Alexandr Plushev',
    play: false,
  },
];
